export const mockServices = [
  {
    id: '1',
    name: 'Physical Therapy',
    slug: 'physical-therapy',
    description: 'Evidence-based treatments to restore movement, reduce pain, and improve quality of life.',
    longDescription: 'Our licensed physical therapists use the latest evidence-based techniques to help you recover from injury, surgery, or chronic conditions. We create personalised plans addressing your specific goals.',
    icon: '🦴',
    conditions: ['Post-surgical rehab', 'Sports injuries', 'Chronic pain', 'Balance disorders'],
  },
  {
    id: '2',
    name: 'Occupational Therapy',
    slug: 'occupational-therapy',
    description: 'Helping patients regain independence in everyday activities after injury or illness.',
    longDescription: 'Occupational therapists focus on restoring your ability to perform daily tasks — from dressing and cooking to returning to work — using adaptive strategies and therapeutic exercise.',
    icon: '🤝',
    conditions: ['Upper-limb rehabilitation', 'Fine motor skills', 'Cognitive rehab', 'Home modification'],
  },
  {
    id: '3',
    name: 'Pelvic Health',
    slug: 'pelvic-health',
    description: 'Specialised care for pelvic floor dysfunction in both women and men.',
    longDescription: 'Our pelvic health specialists treat a range of conditions through internal and external manual therapy, biofeedback, and therapeutic exercise in a compassionate, private setting.',
    icon: '💙',
    conditions: ['Incontinence', 'Pelvic pain', 'Postpartum recovery', 'Prenatal support'],
  },
  {
    id: '4',
    name: 'Sports Performance',
    slug: 'sports-performance',
    description: 'Optimise athletic performance and prevent injury with sport-specific training.',
    longDescription: 'From youth athletes to weekend warriors, our sports performance program combines biomechanical analysis, strength training, and movement efficiency coaching.',
    icon: '🏃',
    conditions: ['Injury prevention', 'Return-to-sport', 'Speed & agility', 'Sports-specific strength'],
  },
  {
    id: '5',
    name: 'TeleHealth',
    slug: 'telehealth',
    description: 'Connect with your therapist from home via secure video appointments.',
    longDescription: 'Receive the same high-quality care from the comfort of your home. Our HIPAA-compliant platform supports evaluation, exercise instruction, and progress review.',
    icon: '💻',
    conditions: ['Follow-up visits', 'Home exercise review', 'Remote consultations', 'Chronic condition management'],
  },
  {
    id: '6',
    name: 'Dry Needling',
    slug: 'dry-needling',
    description: 'Target myofascial trigger points to relieve pain and restore muscle function.',
    longDescription: 'Certified therapists insert fine monofilament needles into trigger points, releasing muscle tension and reducing referred pain patterns rapidly.',
    icon: '🩺',
    conditions: ['Trigger point pain', 'Muscle tightness', 'Headaches', 'Tendinopathies'],
  },
]

export const mockLocations = [
  {
    id: 'loc-1',
    name: 'CORA Physical Therapy – Downtown Orlando',
    address: '123 Orange Ave',
    city: 'Orlando',
    state: 'FL',
    zip: '32801',
    phone: '407-555-0101',
    hours: 'Mon–Fri 7am–7pm, Sat 8am–2pm',
    services: ['Physical Therapy', 'Dry Needling', 'Sports Performance'],
    lat: 28.5384,
    lng: -81.3789,
  },
  {
    id: 'loc-2',
    name: 'CORA Physical Therapy – Winter Park',
    address: '456 Park Ave N',
    city: 'Winter Park',
    state: 'FL',
    zip: '32789',
    phone: '407-555-0202',
    hours: 'Mon–Fri 8am–6pm',
    services: ['Physical Therapy', 'Pelvic Health', 'TeleHealth'],
    lat: 28.5999,
    lng: -81.3514,
  },
  {
    id: 'loc-3',
    name: 'CORA Physical Therapy – Lake Nona',
    address: '789 Narcoossee Rd',
    city: 'Orlando',
    state: 'FL',
    zip: '32832',
    phone: '407-555-0303',
    hours: 'Mon–Fri 7am–7pm',
    services: ['Physical Therapy', 'Occupational Therapy', 'Sports Performance'],
    lat: 28.3861,
    lng: -81.2522,
  },
  {
    id: 'loc-4',
    name: 'CORA Physical Therapy – Tampa Westshore',
    address: '321 S Dale Mabry Hwy',
    city: 'Tampa',
    state: 'FL',
    zip: '33609',
    phone: '813-555-0404',
    hours: 'Mon–Fri 7am–7pm, Sat 8am–12pm',
    services: ['Physical Therapy', 'Dry Needling', 'Pelvic Health'],
    lat: 27.9506,
    lng: -82.4572,
  },
  {
    id: 'loc-5',
    name: 'CORA Physical Therapy – Gainesville',
    address: '500 NW 8th Ave',
    city: 'Gainesville',
    state: 'FL',
    zip: '32601',
    phone: '352-555-0505',
    hours: 'Mon–Fri 8am–6pm',
    services: ['Physical Therapy', 'TeleHealth', 'Sports Performance'],
    lat: 29.6516,
    lng: -82.3248,
  },
]
